# config/meta.yml

meta_product_name: "HarmonyCar"
meta_title: "HarmonyCar - Gérez vos véchiules avec un application"
meta_description: "Gérez vos véchiules avec un application"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
