# config/meta.yml

meta_product_name: "HarmonyCar"
meta_title: "HarmonyCar - Gérez vos véchiules avec une application"
meta_description: "Gérez vos véchiules avec une application"
meta_image: "cover.png"
